faucets/faucets/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gerhans.urls')),


]
if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

faucets/gerhans/urls.py
from django.urls import path
from .views import *
app_name = 'gerhans'

urlpatterns = [
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', GSLoginView.as_view(), name='login'),
    path('accounts/logout/', GSLogoutView.as_view(), name='logout'),
    # path('contacts/', contacts, name='contacts'),
    # path('news/', news, name='news'),
    # path('categories/', categories, name='categories'),
    # path('faucets/', ProductList.as_view(), name='faucets'),
    # path('basins/', ProductList.as_view(), name='basins'),
    # path('accessories/', ProductList.as_view(), name='accessories'),
    # path('favorites/', FavoritesList, name='favorites'),
    # path('sewerage/', ProductList.as_view(), name='sewerage'),
    # path('garden/', ProductList.as_view(), name='garden'),
    # path('financial_support/', financial_support, name='financial_support'),
    # path('basket/', basket, name='basket'),    # path('temporarily/', temporarily, name='temporarily'),
    # path('delivery/', delivery, name='delivery'),    # path('volunteering_help/', volunteering_help, name='volunteering_help'),

]

faucets/gerhans/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from django.core.validators import RegexValidator


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True, verbose_name='Оповещать о новинках?')

    class Meta(AbstractUser.Meta):
        pass

class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'
        ordering = ['name']
    # order = models.SmallIntegerField(default=0, db_index=True, verbose_name='Порядок')
    # super_rubric = models.ForeignKey('SuperRubric', on_delete=models.PROTECT, null=True, blank=True, verbose_name='Надрубрика')

# class SuperRubricManager(models.Manager):
#     def get_queryset(self):
#         return super().get_queryset().filter(super_rubric__isnull=True)
#
# class SuperRubric(Categories):
#     objects = SuperRubricManager()
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         proxy = True
#         ordering = ('order', 'name')
#         verbose_name = 'Надрубрика'
#         verbose_name_plural = 'Надрубрики'
#
#
# class SubRubricManager(models.Manager):
#     def get_queryset(self):
#         return super().get_queryset().filter(super_rubric__isnull=False)
#
# class SubRubric(Categories):
#     objects = SubRubricManager()
#     def __str__(self):
#         return '%s - %s' % (self.super_rubric.name, self.name)
#
#     class Meta:
#         proxy = True
#         ordering = ('super_rubric__order', 'super_rubric__name', 'order', 'name')
#         verbose_name = 'Подрубрика'
#         verbose_name_plural = 'Подрубрики'

# class Product(models.Model):
#     # Product_category = [
#     #
#     #     (1, 'Faucet'),
#     #     (2, 'Basin'),
#     #     (3, 'Accessory'),
#     #     (4, 'Gardeneqm'),
#     #     (5, 'Sewerage')
#     # ]
#     name = models.CharField('Наименование', blank=True, max_length=30, help_text="Артикул")
#
#     rubric = models.ForeignKey('Rubric', null=True, on_delete=models.PROTECT, verbose_name='Категория')
#     # categories = models.ForeignKey('Categories', null=True, on_delete=models.PROTECT, choices=Product_category,help_text="Категория")
#     sku = models.CharField('Артикул', blank=True, max_length=20, help_text="Артикул")
#     upc = models.CharField('UPC', blank=False, max_length=20, help_text="Внутренний код")
#     ean = models.CharField('EAN', blank=True, max_length=20, help_text="Штрихкод")
#     jan = models.CharField('JAN', blank=True, max_length=20, help_text="Артикул")
#     isbn = models.CharField('ISBN', blank=True, max_length=20, help_text="Артикул")
#     mpn = models.CharField('MPN', blank=True, max_length=20, help_text="Артикул")
#     location = models.CharField('Размещение', blank=True, max_length=20, help_text="Артикул")
#     quantity = models.CharField('Количество', blank=True, max_length=20, help_text="Артикул")
#     model = models.CharField('Модель', blank=True, max_length=20, help_text="На упаковке")
#     manufacturer = models.CharField('Производитель', blank=True, max_length=20, help_text="Артикул")
#     image_name = models.CharField('Ссылка на фото', blank=True, max_length=20, help_text="ссылка")
#     foto = models.ImageField(upload_to='images', blank=True, verbose_name='Изображение')
#     shipping = models.CharField('Пересылка', blank=True, max_length=20, help_text="Артикул")
#     price = models.DecimalField('Цена', blank=True, help_text="Цена", max_digits=8, decimal_places=2)
#     points = models.CharField('Баллы', blank=True, max_length=20, help_text="Артикул")
#     date_added = models.DateTimeField('Дата добавления', auto_now_add=True, db_index=True)
#     date_modified = models.DateTimeField('Дата изменений', auto_now_add=True, db_index=True)
#     date_available = models.DateTimeField('Дата поступления', auto_now_add=True, db_index=True)
#     weight = models.CharField('Вес', blank=True, max_length=20, help_text="Артикул")
#     weight_unit = models.CharField('Вес нетто', blank=True, max_length=20, help_text="Артикул")
#     length = models.CharField('Длина', blank=True, max_length=20, help_text="Артикул")
#     width = models.CharField('Ширина', blank=True, max_length=20, help_text="Артикул")
#     height = models.CharField('Высота', blank=True, max_length=20, help_text="Артикул")
#     length_unit = models.CharField('Габарит', blank=True, max_length=20, help_text="Артикул")
#     status = models.CharField('Наличие', blank=True, max_length=20, help_text="Артикул")
#     tax_class_id = models.CharField('Налог', blank=True, max_length=20, help_text="Артикул")
#     seo_keyword = models.CharField('Url ЧПУ', blank=True, max_length=20, help_text="Артикул")
#     description = models.CharField('Описание', blank=True, max_length=20, help_text="Артикул")
#     meta_title = models.CharField('title', blank=True, max_length=20, help_text="Артикул")
#     meta_description = models.CharField('Снипет', blank=True, max_length=20, help_text="Артикул")
#     meta_h1 = models.CharField('Заголовок H1', blank=True, max_length=20, help_text="Артикул")
#     meta_keywords = models.CharField('Ключевые слова', blank=True, max_length=20, help_text="Артикул")
#     stock_status_id = models.CharField('Наличие в продаже', blank=True, max_length=20, help_text="Артикул")
#     store_ids = models.CharField('Магазин', blank=True, max_length=20, help_text="Артикул")
#     layout = models.CharField('Сорт', blank=True, max_length=20, help_text="Артикул")
#     related_ids = models.CharField('Аналоги', blank=True, max_length=20, help_text="Артикул")
#     tags = models.CharField('Тэги', blank=True, max_length=20, help_text="Артикул")
#     sort_order = models.CharField('Сортировка', blank=True, max_length=20, help_text="Артикул")
#     subtract = models.CharField('Резервирование', blank=True, max_length=20, help_text="Артикул")
#     minimum = models.CharField('Минимальный остаток', blank=True, max_length=20, help_text="Артикул")
#
#     class Meta:
#         verbose_name = 'Товар'
#         verbose_name_plural = 'Товары'
#
#
#

# class News(models.Model):
#     article = models.CharField(max_length=20, help_text="Enter field documentation")
#     text_news = models.TextField(max_length=20, help_text="Enter field documentation")
#     data = models.DateTimeField(blank=True, verbose_name="Дата")


#
#
class OrderItem(models.Model):
    name = models.CharField('Заводчик', max_length=30, help_text="Фамилия и имя")
    # phone = models.CharField(max_length=10, help_text="Номер телефона")
    phoneNumberRegex = RegexValidator(regex=r"^\+?1?\d{8,15}$")
    phone = models.CharField('Телефон', validators=[phoneNumberRegex], max_length=16, unique=True)
    article = models.CharField('Артикул', max_length=20, help_text="Артикул")
    message = models.TextField('Замечания', max_length=100, help_text="Замечания")
    order_data = models.DateTimeField(verbose_name="Дата")


#
#
class Favorites(models.Model):
    name = models.CharField('Волонтер', max_length=30, help_text="Фамилия и имя")
    # phone = models.CharField(max_length=10, help_text="Номер телефона")
    phoneNumberRegex = RegexValidator(regex=r"^\+?1?\d{8,15}$")
    phone = models.CharField('Телефон', validators=[phoneNumberRegex], max_length=16, unique=True)
    article = models.CharField('Артикул', max_length=20, help_text="Артикул")
    order_data = models.DateTimeField(verbose_name="Дата")
    start_time = models.DateTimeField(verbose_name="Начало")
    end_time = models.DateTimeField(verbose_name="Окончание")
    message = models.TextField('Замечания', max_length=100, help_text="Замечания")

faucets/gerhans/forms.py
from django.forms import ModelForm, TextInput, DateTimeInput, Textarea
from .models import *
from django import forms

# class SubRubricForm(forms.ModelForm):
#     super_rubric = forms.ModelChoiceField(
#         queryset=SuperRubric.objects.all(),empty_label=None,
#         label='Надрубрика', required=True)
#
#     class Meta:
#         model = SubRubric
#         fields = '__all__'

#
class AdFavoritesList(forms.ModelForm):
    class Meta:
        model = Favorites
        fields = '__all__'
#
#
class AdBasketForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

faucets/gerhans/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


@login_required
def profile(request):
    return render(request, 'gerhans/profile.html')

# Create your views here.
def other_page(request, page):
    try:
        template = get_template('gerhans/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

def index(request):
    return render(request, 'gerhans/index.html')


# def about(request):
#     return render(request, 'gerhans/about.html')
#
#
# def contacts(request):
#     return render(request, 'gerhans/contacts.html')
#
#
# def news(request):
#     return render(request, 'gerhans/news.html')
#
#
# def gift(request):
#     return render(request, 'gerhans/gift.html')
#
#
# def delivery(request):
#     return render(request, 'gerhans/delivery.html')
#
#
# def categories(request):
#     return render(request, 'gerhans/categories.html')
#
#
#
# class ProductList(ListView):
#     paginate_by = 6
#     model = Product
#     template_name = 'gerhans/faucets.html'
#     context_object_name = 'productlist'
#     extra_context = {'title':'Смесители'}
#
#
#
class GSLoginView(LoginView):
    template_name = 'gerhans/login.html'

class GSLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'gerhans/logout.html'

# # def garden(request):
# #
# #     pets = items.objects.all()
# #     return render(request, 'gerhans/garden.html',{'item': items})
#
# class GardenItemList(ListView):
#     paginate_by = 3
#     model = Product
#     template_name = 'gerhans/garden.html'
#     context_object_name = 'gardenitem'
#     extra_context = {'title':'Садовое оборудование'}
#
# class SewerageList(ListView):
#     paginate_by = 3
#     model = Product
#     template_name = 'gerhans/sewerage.html'
#     context_object_name = 'sewerageitem'
#     extra_context = {'title':'Садовое оборудование'}
#
# # def sewerage(request):
# #
# #     pets = items.objects.all()
# #     return render(request, 'gerhans/sewerage.html',{'item': items})
#
# # def favorites(request):
# #
# #     items = items.objects.all()
# #     return render(request, 'gerhans/favorites.html',{'item': items})
#
#
# def basket(request):
#     if request.method == "POST":
#         form = AdBasketForm(request.POST)
#         if form.is_valid():
#             form.save()
#     else:
#         form = AdBasketForm()
#
#     return render(request, 'gerhans/basket.html',{'form': form})
#
#
# def FavoritesList(request):
#     if request.method == 'POST':
#         form = AdFavoritesList(request.POST)
#         if form.is_valid():
#             form.save()
#     else:
#         form = AdFavoritesList()
#
#     return render(request, 'gerhans/favorites.html',{'form': form})
#
#
# # def transportation_order(request):
# #     if request.method == 'POST':
# #         form = AdTransportHelpForm(request.POST)
# #         if form.is_valid():
# #             form.save()
# #     else:
# #         form = AdTransportHelpForm()
# #
# #     return render(request, 'gerhans/transportation_order.html',{'form': form})
#
#
#
# # def volunteering_help(request):
# #     if request.method == 'POST':
# #         form = AdVolOrderForm(request.POST)
# #         if form.is_valid():
# #             form.save()
# #     else:
# #         form = AdVolOrderForm()
# #     return render(request, 'gerhans/volunteering_help.html',{'form': form})
#
#
# def financial_support(request):
#     return render(request, 'gerhans/financial_support.html')
#
#
# def parts(request):
#     return render(request, 'gerhans/parts.html')
#
#
# def food_medicines_help(request):
#     if request.method == 'POST':
#         form = AdFoodMedicinesHelpForm(request.POST)
#         if form.is_valid():
#             form.save()
#     else:
#         form = AdFoodMedicinesHelpForm()
#     return render(request, 'gerhans/food_medicines_help.html',{'form': form})
#

faucets/gerhans/templates/gerhans/about.html
{% extends 'gerhans/basic.html' %}
{% load static %}

{% block title %}
О нас
{% endblock %}

{% block content %}

		<section class="about-us-page" id="about-us">
			<div class="aboutus">
				<h2>О нас</h2>


				<p>
					Gerhans-премиальная сантехника.
				</p>

				<div class="about-us-sotial">
					<p>Связаться с нами можно написав в соц. сетях.
				</p>

				 <div class="double-sotial">
					<a class="vc" href="https://instagram.com/ledeme_minsk?igshid=OGQ5ZDc2ODk2ZA=="><svg width="49" height="49" viewBox="0 0 49 49" fill="none" xmlns="http://www.w3.org/2000/svg">
					<circle cx="24.5" cy="24.5" r="23.5" stroke="#FFC41E" stroke-width="2"/>
					<path d="M38.3122 19.219C38.5218 18.5157 38.3122 18 37.3211 18H34.0379C33.2025 18 32.8207 18.4461 32.6111 18.9361C32.6111 18.9361 30.9418 23.0482 28.5764 25.7145C27.8128 26.4903 27.464 26.7353 27.0478 26.7353C26.8397 26.7353 26.5373 26.4903 26.5373 25.7871V19.219C26.5373 18.3751 26.2963 18 25.6001 18H20.441C19.92 18 19.6056 18.3902 19.6056 18.7622C19.6056 19.5607 20.7883 19.7453 20.9096 21.9956V26.8775C20.9096 27.9467 20.7195 28.1418 20.3003 28.1418C19.1879 28.1418 16.4811 24.0146 14.8747 19.29C14.5618 18.372 14.2459 18.0015 13.4075 18.0015H10.1258C9.18714 18.0015 9 18.4477 9 18.9377C9 19.8178 10.1124 24.1734 14.1815 29.934C16.8943 33.8676 20.7135 36 24.1928 36C26.2783 36 26.5358 35.5266 26.5358 34.71V31.7367C26.5358 30.79 26.7349 30.5994 27.3951 30.5994C27.8802 30.5994 28.7156 30.8474 30.6634 32.7424C32.8881 34.9897 33.2564 35.9985 34.5065 35.9985H37.7882C38.7254 35.9985 39.194 35.5251 38.9245 34.5905C38.6295 33.6604 37.5666 32.3068 36.1563 30.7053C35.3898 29.7918 34.2445 28.8088 33.8956 28.3173C33.4091 27.6836 33.5498 27.4038 33.8956 26.8412C33.8971 26.8427 37.896 21.1533 38.3122 19.219Z" fill="#E8A700"/>
					</svg></a>
			                               <a class="ok" href="https://instagram.com/ledeme_minsk?igshid=OGQ5ZDc2ODk2ZA=="><svg width="49" height="49" viewBox="0 0 49 49" fill="none" xmlns="http://www.w3.org/2000/svg">
											<circle cx="24.5" cy="24.5" r="23.5" stroke="#FFC41E" stroke-width="2"/>
											<path d="M24.4964 19.9981C22.0175 19.9981 19.9945 22.0211 19.9945 24.5C19.9945 26.9789 22.0175 29.0019 24.4964 29.0019C26.9752 29.0019 28.9982 26.9789 28.9982 24.5C28.9982 22.0211 26.9752 19.9981 24.4964 19.9981ZM37.9985 24.5C37.9985 22.6357 38.0154 20.7884 37.9107 18.9275C37.806 16.766 37.3129 14.8477 35.7324 13.2672C34.1485 11.6832 32.2336 11.1935 30.0722 11.0888C28.2079 10.9841 26.3606 11.001 24.4997 11.001C22.6355 11.001 20.7882 10.9841 18.9273 11.0888C16.7659 11.1935 14.8477 11.6866 13.2671 13.2672C11.6832 14.8511 11.1935 16.766 11.0888 18.9275C10.9841 20.7917 11.001 22.6391 11.001 24.5C11.001 26.3609 10.9841 28.2116 11.0888 30.0725C11.1935 32.234 11.6866 34.1523 13.2671 35.7328C14.851 37.3168 16.7659 37.8065 18.9273 37.9112C20.7916 38.0159 22.6389 37.999 24.4997 37.999C26.364 37.999 28.2113 38.0159 30.0722 37.9112C32.2336 37.8065 34.1518 37.3134 35.7324 35.7328C37.3163 34.1489 37.806 32.234 37.9107 30.0725C38.0188 28.2116 37.9985 26.3643 37.9985 24.5ZM24.4964 31.4268C20.6632 31.4268 17.5697 28.3332 17.5697 24.5C17.5697 20.6668 20.6632 17.5732 24.4964 17.5732C28.3295 17.5732 31.423 20.6668 31.423 24.5C31.423 28.3332 28.3295 31.4268 24.4964 31.4268ZM31.7067 18.9072C30.8118 18.9072 30.089 18.1845 30.089 17.2895C30.089 16.3945 30.8118 15.6718 31.7067 15.6718C32.6017 15.6718 33.3244 16.3945 33.3244 17.2895C33.3247 17.502 33.283 17.7125 33.2018 17.9089C33.1206 18.1053 33.0015 18.2837 32.8512 18.434C32.7009 18.5843 32.5225 18.7034 32.3261 18.7846C32.1297 18.8658 31.9192 18.9075 31.7067 18.9072Z" fill="#E8A700"/>
											</svg></a>
			    </div>
                </div>
			</div>
		</section>
{% endblock %}

faucets/gerhans/templates/gerhans/basic.html
{% load bootstrap4 %}
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
        content="width=device-width, initial-scale=1, shink-to-fit=no">
        <title>{% block title %}{% endblock %} - Сайт Gerhans
        </title>
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css"
        href="{% static 'gerhans/style.css' %}">
        {% bootstrap_javascript jquery='slim' %}
</head>
<body class="container-fluid">
    <header class="mb-4">
        <h1 class="display-1 text-center">Категории</h1>
    </header>
    <div class="row">
        <ul class="col nav justify-content-end border">
                <li class="nav-item"><a class="nav-link" href="#">Регистрация</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                       data-toggle="dropdown"
                    href="#" role="button" aria-haspopup="true"
                    aria-expanded="false">Профиль</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'gerhans:profile' %}">Мои заказы</a>
                        <a class="dropdown-item" href="#">Изменить личные данные</a>
                        <a class="dropdown-item" href="#">Изменить пароль</a>
                            <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'gerhans:logout' %}">Выйти</a>
                            <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Удалить</a>
                    </div>
                </li>
            {% else %}
            <li class="nav-item"><a class="nav-link"
            href="{% url 'gerhans:login' %}">Вход</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="row">
        <nav class="col-md-auto nav flex-column border">
            <a class="nav-link root"
               href="{% url 'gerhans:index' %}">Главная</a>
            <a class="nav-link root"
               href="{% url 'gerhans:other' page='about' %}">О нас</a>
            <span class="nav-link root font-weight-bold">Смесители</span>
            <a class="nav-link" href="#">для ванной</a>
            <a class="nav-link" href="#">для биде</a>
            <a class="nav-link" href="#">для кухни</a>
            <a class="nav-link" href="#">для туалета</a>
            <a class="nav-link" href="#">для душа</a>
            <span class="nav-link root font-weight-bold">Аксессуары</span>
            <a class="nav-link" href="#">полки</a>
            <a class="nav-link" href="#">вешалки</a>
            <a class="nav-link" href="#">урны</a>
            <a class="nav-link" href="#">для туалета</a>
            <a class="nav-link" href="#">для душа</a>
        </nav>
        <section class="col border py-2">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </section>
    </div>
    <footer class="mt-3">
        <p class="text-right font-italic">&copy; читетели.</p>
    </footer>

</body>
</html>

faucets/gerhans/templates/gerhans/categories.html
{% extends 'gerhans/base.html' %}
{% load static %}

{% block title %}
Как помочь
{% endblock %}

{% block content %}
	<section class="top-page3" >
		<h3 id="help">Каталог</h3>
			<ul class="variant-list">
				<li >
					<a class="variant_1" href="{% url 'faucets' %}"><img src="{% static 'gerhans/images/faucets-icon.svg' %}"></a>
					<p>Смесители</p>
				</li>
				<li >
					<a class="variant_2" href="{% url 'basins' %}"><img src="{% static 'gerhans/images/variant_2.svg' %}"></a>
					<p> Мойки</p>
				</li>
				<li >
					<a class="variant_3" href="{% url 'accessories' %}"><img src="{% static 'gerhans/images/variant_3.svg' %}"></a>
					<p>Аксессуары</p>
				</li>
				<li >
					<a class="variant_4" href="{% url 'garden' %}"><img src="{% static 'gerhans/images/variant_4.svg' %}"></a>
					<p>Садовый полив</p>
				</li>
				<li>
					<a class="variant_5" href="{% url 'sewerage' %}"><img src="{% static 'gerhans/images/variant_5.svg' %}"></a>
					<p>Канализация</p>
				</li>
			</ul>
	</section>
{% endblock %}

faucets/gerhans/templates/gerhans/delivery.html
{% extends 'gerhans/base.html' %}
{% load static %}

{% block title %}
Транспортировка
{% endblock %}

{% block content %}
<div class="autohelp-page-top" id="transports">
				<div class="left-line"></div>
				<div class="autohelp-logo"></div>
				<div class="right-line"></div>
			</div>
			<div class="autohelp-page">
					<h2>Автопомощь</h2>
					<p>Важной помощью будет транспортировка. Необходимо отвозить животных в ветеринарную клинику в
						сопровождении нашего волонтера или привозить еду. Если у вас есть автомобиль, немного свободного
						времени и доброе сердце - будем вам рады.
					</p>
				<a href="{% url 'transportation_order' %}" ><button class="autohelp-zakaz">Оставить заявку</button></a>

			</div>
{% endblock %}

faucets/gerhans/templates/gerhans/financial_support.html
{% extends 'gerhans/base.html' %}
{% load static %}

{% block title %}
Материальная помощь
{% endblock %}

{% block content %}
<section class="finance-page" >
			<div class="finance-page-top" id="finance">
				<div class="left-line"></div>
				<div class="finance-logo"></div>
				<div class="right-line"></div>
			</div>
			<div class="help-block">
				<div class="zagolovok">
					<h3>Финансовая поддержка</h3>
				</div>
				<div class="about-finance">
					<p> Такая помощь необходима для оплаты стерилизации, прививок, лечения больных животных, покупка
						корма и других жизненно необходимых вещей.</p>
				</div>
			</div>
				<div class="point-help">
					<div class="schet">
						<h2>Расчетный счет в Банке</h2>
						<div>
							<p>Gerhans</p>
							<p>УНП: ХХХХХХХХХХХХХХ<br>
								<strong>Текущий (расчетный) счет в BYN:</strong>
								BYХХХХХХХХХХХХХХХХХХХХХХХХ <br>
								ЗАО 'ХХХХХХХХХХХ'<br>
								БИК: ХХХХХХХХХХ</p>
								<button>Быстрый платеж</button>
						</div>
					</div>
					<div class="money-point">
						<h2>Точки в городе</h2>
						<p>Наши розничные магазины:</p>

						<p>
						</p>

					</div>
				</div>


		</section>
{% endblock %}